# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-mock}
      - DATABASE_URL=sqlite:///app/data/analyses.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped